#  ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓  ┳┓┏┓┏┓┏┓┓┏
#  ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃━━┣┫┃┃ ┃┃ ┗┫
#  ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛  ┻┛┗┛┗┛┗┛┗┛
#                              



# Use custom format:
format="$directory$git_branch$git_status$character"

# Prompt symbols 
[character]
success_symbol = "[ ᐉ](bright-green bold)"
error_symbol = "[ ᐉ](bright-red bold)"
vicmd_symbol = "[ ᐉ](bright-yellow bold)"

# Directory
[directory]
format = "[▉]($style)[(bg:black fg:none) $path ](inverted)[▕]($style)"
style = "bg:black fg:none"

# Git branch
[git_branch]
format = "[▉]($style)[(bg:black fg:none) \ue725 $branch ](inverted)[▕]($style)"
style = "bg:black fg:none"

# Git status
[git_status]
conflicted = '󰷂'
ahead = ''
behind = ''
diverged = '󱡷'
up_to_date = ''
untracked = ''
stashed = ''
modified = ''
staged = ''
renamed = ''
deleted = '󰆴'
format = "[▉]($style)[(bg:black fg:none) $all_status $ahead_behind ](inverted)[▕]($style)"
style = "bg:black fg:none"
